apiVersion: apps/v1
kind: Deployment
metadata:
  name: WeatherApi-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: WeatherApi
  template:
    metadata:
      labels:
        app: WeatherApi
    spec:
      containers:
      - name: WeatherApi-container
        image: gcr.io/dps-parent-project/WeatherApi:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "200Mi"
            cpu: "700m"
        ports:
        - containerPort: 80
