apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
  namespace: sat-k8s
spec:
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi-container
        image: gcr.io/dps-parent-project/weatherapi:tagversion
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
